name: Build & deploy web

env:
  REGISTRY_IMAGE: ghcr.io/prokleta-kuja/selflix

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/api/**/*"
      - "src/web/**/*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Generate env variables
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "DATE=$(date +'%Y-%m-%d')" >> ${GITHUB_ENV}
          echo "VERSION=$(date +'%Y.%m.%d')-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
      - name: Restore dependencies
        working-directory: src/api
        run: dotnet restore
      - name: Build
        working-directory: src/api
        run: dotnet build --no-restore
      - name: Publish
        working-directory: src/api
        run: dotnet publish /p:Version=${{ env.VERSION }} -c Release --no-restore -o out
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: src/web/package-lock.json
      - name: Install npm dependencies
        working-directory: src/web
        run: npm ci
      - name: Generate static files
        working-directory: src/web
        run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:latest
            ${{ env.REGISTRY_IMAGE }}:${{ env.DATE }}
            ${{ env.REGISTRY_IMAGE }}:${{ github.RUN_NUMBER }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Prepare SSH
        env:
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_script: ${{ secrets.SSH_SCRIPT }}
        run: |
          mkdir ~/.ssh          
          echo "$remote_key" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          hosts="$(dig +short "$remote_host" | grep -v '\.$' | sed -z 's|\n|,|g')$remote_host"
          ssh-keyscan -p $remote_port -H "$hosts" > ~/.ssh/known_hosts
          ssh -p $remote_port -i ~/.ssh/id_rsa $remote_user@$remote_host "$remote_script ${{ github.RUN_NUMBER }}"
          rm ~/.ssh/id_rsa

  notify:
    name: Notify
    runs-on: ubuntu-latest
    if: always()
    needs: [build, deploy]
    steps:
      - name: Success
        if: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' }}
        continue-on-error: true
        env:
          notify_cred: ${{ secrets.NOTIFY_CRED }}
          notify_url: ${{ secrets.NOTIFY_URL }}
          app_url: ${{ secrets.URL }}
          action_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl \
            -u $notify_cred \
            -H "Title: Selflix deployed" \
            -H "Tags: octopus" \
            -H "Priority: 3" \
            -H "Actions: view, GitHub, $action_url, clear=true; \
                         view, App, $app_url, clear=true" \
            -H "Content-Type: text/plain" \
            -d $'${{ github.REPOSITORY }} deployed.' \
            $notify_url
      - name: Failure
        if: ${{ needs.build.result == 'failure' || needs.deploy.result == 'failure' }}
        continue-on-error: true
        env:
          notify_cred: ${{ secrets.NOTIFY_CRED }}
          notify_url: ${{ secrets.NOTIFY_URL }}
          app_url: ${{ secrets.URL }}
          action_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl \
            -u $notify_cred \
            -H "Title: Selflix wasn't deployed" \
            -H "Tags: cursing_face" \
            -H "Priority: 4" \
            -H "Actions: view, GitHub, $action_url" \
            -H "Content-Type: text/plain" \
            -d $'${{ github.REPOSITORY }} failed.' \
            $notify_url
